#!/usr/bin/env python3
"""Generate Julia and Raku revision-3 wire records from api.json."""

from __future__ import annotations

import argparse
import difflib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODEL = ROOT / "bindings/api.json"
JULIA_OUTPUT = ROOT / "bindings/julia/Duallity/src/GeneratedAbi.jl"
RAKU_OUTPUT = ROOT / "bindings/raku/lib/Duallity/ConfigAbi.rakumod"

SCALARS = {
    "uint8_t": "UInt8", "uint32_t": "UInt32", "uint64_t": "UInt64",
    "int32_t": "Int32",
    "double": "Float64",
}


def field_declaration(value: str) -> tuple[str, str, int | None]:
    match = re.fullmatch(r"(.+?)\s+([A-Za-z_][A-Za-z_0-9]*)(?:\[(\d+)\])?", value)
    if match is None:
        raise ValueError(f"unsupported C record field: {value}")
    c_type, name, count = match.groups()
    return c_type, name, int(count) if count else None


def julia_type(c_type: str, count: int | None) -> str:
    if c_type in SCALARS:
        base = SCALARS[c_type]
    elif c_type == "DuallityRecordHeaderV1":
        base = c_type
    elif c_type.startswith("const ") and c_type.endswith("*"):
        target = c_type[len("const ") : -1]
        base = f"Ptr{{{SCALARS.get(target, target)}}}"
    else:
        raise ValueError(f"unsupported C record type: {c_type}")
    return f"NTuple{{{count},{base}}}" if count else base


def blank_value(c_type: str, count: int | None, record_name: str) -> str:
    if c_type == "DuallityRecordHeaderV1":
        return f"record_header({record_name})"
    if c_type.endswith("*"):
        return f"{julia_type(c_type, None)}(0)"
    if c_type == "double":
        return "0.0"
    base = f"{julia_type(c_type, None)}(0)"
    return f"ntuple(_ -> {base}, {count})" if count else base


def render_julia(model: dict) -> str:
    config = model["configAbi"]
    fzf = model["fzfAbi"]
    lines = [
        "# Generated by scripts/generate-config-abi.py from bindings/api.json.",
        "# Do not edit by hand.",
        f"const ABI_VERSION = UInt32({model['abiVersion']})",
        f"const API_REVISION = UInt32({model['apiRevision']})",
        f"const CONFIG_API_REVISION = UInt32({config['sinceApiRevision']})",
        f"const CONFIG_RECORD_VERSION = UInt32({config['recordVersion']})",
        f"const CONFIG_MAX_OPERATIONS = {config['maxOperations']}",
        f"const CONFIG_MAX_RESTRICTION_PAIRS = {config['maxRestrictionPairs']}",
        f"const CONFIG_MAX_CUSTOM_TEXT_BYTES = {config['maxCustomTextBytes']}",
        f"const FZF_API_REVISION = UInt32({fzf['sinceApiRevision']})",
        f"const FZF_MAX_TOP_K = {fzf['maximumTopK']}",
        f"const FZF_MAX_WORK_UNITS = {fzf['maximumWorkUnits']}",
        "",
    ]
    for key, name, prefix in (
        ("status", "Status", "STATUS_"),
        ("algorithm", "Algorithm", "ALGORITHM_"),
        ("wfstKind", "WfstKind", "WFST_"),
    ):
        lines.append(f"@enum {name}::UInt32 begin")
        for variant, value in model["enums"][key]["values"].items():
            lines.append(f"    {prefix}{variant} = {value}")
        lines.extend(("end", ""))
    lines.append("@enum FzfScheme::UInt32 begin")
    for variant, value in fzf["schemes"].items():
        lines.append(f"    FZF_SCHEME_{variant} = {value}")
    lines.extend(("end", ""))
    for key, name, prefix in (
        ("cachePolicies", "CachePolicy", ""),
        ("operationApplicability", "OperationApplicability", "APPLICABILITY_"),
    ):
        lines.append(f"@enum {name}::UInt32 begin")
        for variant, value in config[key].items():
            lines.append(f"    {prefix}{variant} = {value}")
        lines.extend(("end", ""))

    parsed: dict[str, list[tuple[str, str, int | None]]] = {}
    for record_name, declarations in (config["records"] | fzf["records"]).items():
        fields = [field_declaration(value) for value in declarations]
        parsed[record_name] = fields
        lines.append(f"struct {record_name}")
        for c_type, field_name, count in fields:
            lines.append(f"    {field_name}::{julia_type(c_type, count)}")
        lines.extend(("end", ""))

    lines.extend((
        "record_header(::Type{T}) where {T} =",
        "    DuallityRecordHeaderV1(UInt32(sizeof(T)), CONFIG_RECORD_VERSION, UInt64(0))",
        "",
    ))
    for record_name, fields in parsed.items():
        if record_name == "DuallityRecordHeaderV1":
            lines.append(f"{record_name}() = record_header({record_name})")
            lines.append("")
            continue
        values = ",\n        ".join(
            blank_value(c_type, count, record_name)
            for c_type, _, count in fields
        )
        lines.extend((f"{record_name}() = {record_name}(", f"        {values})", ""))
    return "\n".join(lines)


def raku_fields(record_name: str, declarations: list[str]) -> list[tuple[str, str]]:
    fields: list[tuple[str, str]] = []
    for value in declarations:
        c_type, name, count = field_declaration(value)
        if c_type == "DuallityRecordHeaderV1":
            if count is not None:
                raise ValueError("an array of record headers is unsupported")
            fields.extend((
                ("uint32", "struct-size"),
                ("uint32", "record-version"),
                ("uint64", "header-reserved"),
            ))
            continue
        target = {"uint8_t": "uint8", "uint32_t": "uint32",
                  "uint64_t": "uint64", "double": "num64"}.get(c_type)
        if c_type.startswith("const ") and c_type.endswith("*"):
            # NativeCall CStruct Pointer slots cannot be written through their
            # generated accessors on supported Rakudo versions. A size_t slot
            # has the same C pointer width and alignment and remains writable.
            target = "size_t"
        if target is None:
            raise ValueError(f"unsupported Raku record type: {c_type}")
        label = name.replace("_", "-")
        if count:
            fields.extend((target, f"{label}{index}") for index in range(count))
        else:
            fields.append((target, label))
    if len({name for _, name in fields}) != len(fields):
        raise ValueError(f"duplicate flattened Raku fields: {record_name}")
    return fields


def render_raku(model: dict) -> str:
    config = model["configAbi"]
    lines = [
        "unit module Duallity::ConfigAbi;",
        "",
        "use NativeCall;",
        "",
        "# Generated by scripts/generate-config-abi.py from bindings/api.json.",
        "# Do not edit by hand. Header fields are flattened with the same C layout.",
        f"our constant CONFIG-API-REVISION is export = {config['sinceApiRevision']};",
        f"our constant CONFIG-RECORD-VERSION is export = {config['recordVersion']};",
        f"our constant CONFIG-MAX-OPERATIONS is export = {config['maxOperations']};",
        f"our constant CONFIG-MAX-RESTRICTION-PAIRS is export = {config['maxRestrictionPairs']};",
        f"our constant CONFIG-MAX-CUSTOM-TEXT-BYTES is export = {config['maxCustomTextBytes']};",
        "",
    ]
    for key, name in (
        ("cachePolicies", "CachePolicy"),
        ("operationApplicability", "OperationApplicability"),
    ):
        lines.append(f"our enum {name} is export (")
        for variant, value in config[key].items():
            lines.append(f"    {variant.replace('_', '-')} => {value},")
        lines.extend((");", ""))
    for record_name, declarations in config["records"].items():
        lines.append(f"class {record_name} is repr('CStruct') is export {{")
        for raku_type, field_name in raku_fields(record_name, declarations):
            lines.append(f"    has {raku_type} $.{field_name} is rw;")
        lines.extend(("}", ""))
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    model = json.loads(MODEL.read_text())
    for output, expected in (
        (JULIA_OUTPUT, render_julia(model)),
        (RAKU_OUTPUT, render_raku(model)),
    ):
        if arguments.check:
            actual = output.read_text() if output.exists() else ""
            if actual != expected:
                raise SystemExit("".join(difflib.unified_diff(
                    actual.splitlines(keepends=True),
                    expected.splitlines(keepends=True),
                    fromfile=str(output), tofile="generated expected",
                )) or f"generated ABI is stale: {output}")
        else:
            output.write_text(expected)


if __name__ == "__main__":
    main()
