# Generated from bindings/api.json. Do not edit by hand.
const ABI_VERSION = UInt32(1)
const API_REVISION = UInt32(2)

@enum Status::UInt32 begin
    STATUS_OK = 0
    STATUS_INVALID_ARGUMENT = 1
    STATUS_INVALID_UTF8 = 2
    STATUS_NULL_POINTER = 3
    STATUS_PANIC = 4
    STATUS_INCOMPATIBLE_RESOURCE = 5
    STATUS_PROVIDER_ERROR = 6
    STATUS_LIMIT_EXCEEDED = 7
end

@enum Algorithm::UInt32 begin
    ALGORITHM_STANDARD = 0
    ALGORITHM_TRANSPOSITION = 1
    ALGORITHM_MERGE_AND_SPLIT = 2
    ALGORITHM_DAMERAU_LEVENSHTEIN = 3
end

@enum WfstKind::UInt32 begin
    WFST_LEVENSHTEIN = 0
    WFST_UNIVERSAL_STANDARD = 1
    WFST_UNIVERSAL_TRANSPOSITION = 2
    WFST_UNIVERSAL_MERGE_AND_SPLIT = 3
    WFST_GENERALIZED_STANDARD = 4
    WFST_GENERALIZED_TRANSPOSITION = 5
    WFST_GENERALIZED_MERGE_AND_SPLIT = 6
    WFST_GENERALIZED_PHONETIC = 7
    WFST_FZF = 8
end
