# Generated by scripts/generate-config-abi.py from bindings/api.json.
# Do not edit by hand.
const ABI_VERSION = UInt32(1)
const API_REVISION = UInt32(4)
const CONFIG_API_REVISION = UInt32(3)
const CONFIG_RECORD_VERSION = UInt32(1)
const CONFIG_MAX_OPERATIONS = 4096
const CONFIG_MAX_RESTRICTION_PAIRS = 4096
const CONFIG_MAX_CUSTOM_TEXT_BYTES = 1048576

@enum Status::UInt32 begin
    STATUS_OK = 0
    STATUS_INVALID_ARGUMENT = 1
    STATUS_INVALID_UTF8 = 2
    STATUS_NULL_POINTER = 3
    STATUS_PANIC = 4
    STATUS_INCOMPATIBLE_RESOURCE = 5
    STATUS_PROVIDER_ERROR = 6
    STATUS_LIMIT_EXCEEDED = 7
end

@enum Algorithm::UInt32 begin
    ALGORITHM_STANDARD = 0
    ALGORITHM_TRANSPOSITION = 1
    ALGORITHM_MERGE_AND_SPLIT = 2
    ALGORITHM_DAMERAU_LEVENSHTEIN = 3
end

@enum WfstKind::UInt32 begin
    WFST_LEVENSHTEIN = 0
    WFST_UNIVERSAL_STANDARD = 1
    WFST_UNIVERSAL_TRANSPOSITION = 2
    WFST_UNIVERSAL_MERGE_AND_SPLIT = 3
    WFST_GENERALIZED_STANDARD = 4
    WFST_GENERALIZED_TRANSPOSITION = 5
    WFST_GENERALIZED_MERGE_AND_SPLIT = 6
    WFST_GENERALIZED_PHONETIC = 7
    WFST_FZF = 8
end

@enum CachePolicy::UInt32 begin
    CACHE_ALL = 0
    NO_CACHE = 1
    LRU = 2
end

@enum OperationApplicability::UInt32 begin
    APPLICABILITY_ANY = 0
    APPLICABILITY_EQUAL = 1
    APPLICABILITY_ADJACENT_TRANSPOSE = 2
    APPLICABILITY_LISTED = 3
end

struct DuallityRecordHeaderV1
    struct_size::UInt32
    record_version::UInt32
    reserved::UInt64
end

struct DuallityRestrictionV1
    header::DuallityRecordHeaderV1
    source_data::Ptr{UInt8}
    source_len::UInt64
    target_data::Ptr{UInt8}
    target_len::UInt64
    reserved::NTuple{2,UInt64}
end

struct DuallityOperationV1
    header::DuallityRecordHeaderV1
    consume_x::UInt64
    consume_y::UInt64
    weight::Float64
    applicability::UInt32
    reserved_zero::UInt32
    name_data::Ptr{UInt8}
    name_len::UInt64
    restrictions::Ptr{DuallityRestrictionV1}
    restriction_count::UInt64
    restriction_stride::UInt64
    reserved::NTuple{2,UInt64}
end

struct DuallityGeneralizedLimitsV1
    header::DuallityRecordHeaderV1
    max_query_bytes::UInt64
    max_query_scalars::UInt64
    max_operation_source_scalars::UInt64
    max_operation_query_scalars::UInt64
    max_retained_dictionary_nodes::UInt64
    max_retained_wfst_states::UInt64
    max_paths_per_expansion::UInt64
    max_work_units_per_expansion::UInt64
    reserved::NTuple{2,UInt64}
end

struct DuallityWfstOptionsV1
    header::DuallityRecordHeaderV1
    kind::UInt32
    algorithm::UInt32
    maximum_distance::UInt64
    cache_policy::UInt32
    reserved_zero::UInt32
    cache_capacity::UInt64
    limits::Ptr{DuallityGeneralizedLimitsV1}
    operations::Ptr{DuallityOperationV1}
    operation_count::UInt64
    operation_stride::UInt64
    reserved::NTuple{2,UInt64}
end

struct DuallityCacheStatisticsV1
    header::DuallityRecordHeaderV1
    hits::UInt64
    misses::UInt64
    faults::UInt64
    uncacheable_results::UInt64
    insertions::UInt64
    evictions::UInt64
    raced_publications::UInt64
    clears::UInt64
    resident_states::UInt64
    recency_records::UInt64
    reserved::NTuple{2,UInt64}
end

record_header(::Type{T}) where {T} =
    DuallityRecordHeaderV1(UInt32(sizeof(T)), CONFIG_RECORD_VERSION, UInt64(0))

DuallityRecordHeaderV1() = record_header(DuallityRecordHeaderV1)

DuallityRestrictionV1() = DuallityRestrictionV1(
        record_header(DuallityRestrictionV1),
        Ptr{UInt8}(0),
        UInt64(0),
        Ptr{UInt8}(0),
        UInt64(0),
        ntuple(_ -> UInt64(0), 2))

DuallityOperationV1() = DuallityOperationV1(
        record_header(DuallityOperationV1),
        UInt64(0),
        UInt64(0),
        0.0,
        UInt32(0),
        UInt32(0),
        Ptr{UInt8}(0),
        UInt64(0),
        Ptr{DuallityRestrictionV1}(0),
        UInt64(0),
        UInt64(0),
        ntuple(_ -> UInt64(0), 2))

DuallityGeneralizedLimitsV1() = DuallityGeneralizedLimitsV1(
        record_header(DuallityGeneralizedLimitsV1),
        UInt64(0),
        UInt64(0),
        UInt64(0),
        UInt64(0),
        UInt64(0),
        UInt64(0),
        UInt64(0),
        UInt64(0),
        ntuple(_ -> UInt64(0), 2))

DuallityWfstOptionsV1() = DuallityWfstOptionsV1(
        record_header(DuallityWfstOptionsV1),
        UInt32(0),
        UInt32(0),
        UInt64(0),
        UInt32(0),
        UInt32(0),
        UInt64(0),
        Ptr{DuallityGeneralizedLimitsV1}(0),
        Ptr{DuallityOperationV1}(0),
        UInt64(0),
        UInt64(0),
        ntuple(_ -> UInt64(0), 2))

DuallityCacheStatisticsV1() = DuallityCacheStatisticsV1(
        record_header(DuallityCacheStatisticsV1),
        UInt64(0),
        UInt64(0),
        UInt64(0),
        UInt64(0),
        UInt64(0),
        UInt64(0),
        UInt64(0),
        UInt64(0),
        UInt64(0),
        UInt64(0),
        ntuple(_ -> UInt64(0), 2))
