unit module Duallity::ConfigAbi;

use NativeCall;

# Generated by scripts/generate-config-abi.py from bindings/api.json.
# Do not edit by hand. Header fields are flattened with the same C layout.
our constant CONFIG-API-REVISION is export = 3;
our constant CONFIG-RECORD-VERSION is export = 1;
our constant CONFIG-MAX-OPERATIONS is export = 4096;
our constant CONFIG-MAX-RESTRICTION-PAIRS is export = 4096;
our constant CONFIG-MAX-CUSTOM-TEXT-BYTES is export = 1048576;

our enum CachePolicy is export (
    CACHE-ALL => 0,
    NO-CACHE => 1,
    LRU => 2,
);

our enum OperationApplicability is export (
    ANY => 0,
    EQUAL => 1,
    ADJACENT-TRANSPOSE => 2,
    LISTED => 3,
);

class DuallityRecordHeaderV1 is repr('CStruct') is export {
    has uint32 $.struct-size is rw;
    has uint32 $.record-version is rw;
    has uint64 $.reserved is rw;
}

class DuallityRestrictionV1 is repr('CStruct') is export {
    has uint32 $.struct-size is rw;
    has uint32 $.record-version is rw;
    has uint64 $.header-reserved is rw;
    has size_t $.source-data is rw;
    has uint64 $.source-len is rw;
    has size_t $.target-data is rw;
    has uint64 $.target-len is rw;
    has uint64 $.reserved0 is rw;
    has uint64 $.reserved1 is rw;
}

class DuallityOperationV1 is repr('CStruct') is export {
    has uint32 $.struct-size is rw;
    has uint32 $.record-version is rw;
    has uint64 $.header-reserved is rw;
    has uint64 $.consume-x is rw;
    has uint64 $.consume-y is rw;
    has num64 $.weight is rw;
    has uint32 $.applicability is rw;
    has uint32 $.reserved-zero is rw;
    has size_t $.name-data is rw;
    has uint64 $.name-len is rw;
    has size_t $.restrictions is rw;
    has uint64 $.restriction-count is rw;
    has uint64 $.restriction-stride is rw;
    has uint64 $.reserved0 is rw;
    has uint64 $.reserved1 is rw;
}

class DuallityGeneralizedLimitsV1 is repr('CStruct') is export {
    has uint32 $.struct-size is rw;
    has uint32 $.record-version is rw;
    has uint64 $.header-reserved is rw;
    has uint64 $.max-query-bytes is rw;
    has uint64 $.max-query-scalars is rw;
    has uint64 $.max-operation-source-scalars is rw;
    has uint64 $.max-operation-query-scalars is rw;
    has uint64 $.max-retained-dictionary-nodes is rw;
    has uint64 $.max-retained-wfst-states is rw;
    has uint64 $.max-paths-per-expansion is rw;
    has uint64 $.max-work-units-per-expansion is rw;
    has uint64 $.reserved0 is rw;
    has uint64 $.reserved1 is rw;
}

class DuallityWfstOptionsV1 is repr('CStruct') is export {
    has uint32 $.struct-size is rw;
    has uint32 $.record-version is rw;
    has uint64 $.header-reserved is rw;
    has uint32 $.kind is rw;
    has uint32 $.algorithm is rw;
    has uint64 $.maximum-distance is rw;
    has uint32 $.cache-policy is rw;
    has uint32 $.reserved-zero is rw;
    has uint64 $.cache-capacity is rw;
    has size_t $.limits is rw;
    has size_t $.operations is rw;
    has uint64 $.operation-count is rw;
    has uint64 $.operation-stride is rw;
    has uint64 $.reserved0 is rw;
    has uint64 $.reserved1 is rw;
}

class DuallityCacheStatisticsV1 is repr('CStruct') is export {
    has uint32 $.struct-size is rw;
    has uint32 $.record-version is rw;
    has uint64 $.header-reserved is rw;
    has uint64 $.hits is rw;
    has uint64 $.misses is rw;
    has uint64 $.faults is rw;
    has uint64 $.uncacheable-results is rw;
    has uint64 $.insertions is rw;
    has uint64 $.evictions is rw;
    has uint64 $.raced-publications is rw;
    has uint64 $.clears is rw;
    has uint64 $.resident-states is rw;
    has uint64 $.recency-records is rw;
    has uint64 $.reserved0 is rw;
    has uint64 $.reserved1 is rw;
}
