unit module Duallity::GeneratedAbi;

use NativeCall;
need Vinary::Tree::Interop;

# Code generated by scripts/generate-raku-abi.py from bindings/api.json
# after validating include/duallity.h; DO NOT EDIT.
our constant ABI-VERSION is export = 1;
our constant API-REVISION is export = 6;

our enum Status is export (
    OK => 0,
    INVALID-ARGUMENT => 1,
    INVALID-UTF8 => 2,
    NULL-POINTER => 3,
    PANIC => 4,
    INCOMPATIBLE-RESOURCE => 5,
    PROVIDER-ERROR => 6,
    LIMIT-EXCEEDED => 7,
);

our enum Algorithm is export (
    STANDARD => 0,
    TRANSPOSITION => 1,
    MERGE-AND-SPLIT => 2,
    DAMERAU-LEVENSHTEIN => 3,
);

our enum WfstKind is export (
    LEVENSHTEIN => 0,
    UNIVERSAL-STANDARD => 1,
    UNIVERSAL-TRANSPOSITION => 2,
    UNIVERSAL-MERGE-AND-SPLIT => 3,
    GENERALIZED-STANDARD => 4,
    GENERALIZED-TRANSPOSITION => 5,
    GENERALIZED-MERGE-AND-SPLIT => 6,
    GENERALIZED-PHONETIC => 7,
    FZF => 8,
);

our constant TYPE-KINDS is export = Map.new(
    'DuallityWfst' => 'opaque',
    'VtResource' => 'imported-struct',
);

our constant TYPE-RAKU-REPRESENTATIONS is export = Map.new(
    'DuallityWfst' => 'Pointer',
    'VtResource' => 'Vinary::Tree::Interop::RawResource',
);

our constant TYPE-OWNERSHIP is export = Map.new(
    'DuallityWfst' => 'unique-handle',
    'VtResource' => 'reference-counted-retain',
);

our constant C-SIGNATURES is export = Map.new(
    'duallity_abi_version' => 'DUALLITY_API uint32_t duallity_abi_version(void);',
    'duallity_api_revision' => 'DUALLITY_API uint32_t duallity_api_revision(void);',
    'duallity_last_error_message' => 'DUALLITY_API const char* duallity_last_error_message(void);',
    'duallity_wfst_new' => 'DUALLITY_API DuallityStatus duallity_wfst_new(VtResource dictionary, const uint8_t* query_data, size_t query_len, size_t maximum_distance, uint32_t algorithm, uint32_t kind, DuallityWfst** out_wfst);',
    'duallity_wfst_new_ref' => 'DUALLITY_API DuallityStatus duallity_wfst_new_ref(const VtResource* dictionary, const uint8_t* query_data, size_t query_len, size_t maximum_distance, uint32_t algorithm, uint32_t kind, DuallityWfst** out_wfst);',
    'duallity_wfst_free' => 'DUALLITY_API void duallity_wfst_free(DuallityWfst* wfst);',
    'duallity_wfst_resource' => 'DUALLITY_API DuallityStatus duallity_wfst_resource(const DuallityWfst* wfst, VtResource* out_resource);',
    'duallity_resource_release' => 'DUALLITY_API void duallity_resource_release(VtResource resource);',
    'duallity_wfst_options_default' => 'DUALLITY_API DuallityStatus duallity_wfst_options_default(DuallityWfstOptionsV1* out_options);',
    'duallity_wfst_new_configured_ref' => 'DUALLITY_API DuallityStatus duallity_wfst_new_configured_ref(const VtResource* dictionary, const uint8_t* query_data, size_t query_len, const DuallityWfstOptionsV1* options, DuallityWfst** out_wfst);',
    'duallity_wfst_options_get' => 'DUALLITY_API DuallityStatus duallity_wfst_options_get(const DuallityWfst* wfst, DuallityWfstOptionsV1* out_options);',
    'duallity_wfst_cache_statistics' => 'DUALLITY_API DuallityStatus duallity_wfst_cache_statistics(const DuallityWfst* wfst, DuallityCacheStatisticsV1* out_statistics);',
    'duallity_wfst_cache_clear' => 'DUALLITY_API DuallityStatus duallity_wfst_cache_clear(DuallityWfst* wfst);',
    'duallity_wfst_cache_set_policy' => 'DUALLITY_API DuallityStatus duallity_wfst_cache_set_policy(DuallityWfst* wfst, uint32_t policy, uint64_t capacity);',
    'duallity_wallbreaker_wfst_new_results' => 'DUALLITY_API DuallityStatus duallity_wallbreaker_wfst_new_results(const uint8_t* query_data, size_t query_len, uint32_t algorithm_value, uint64_t maximum_distance, const DuallityWallBreakerResultV1* results, uint64_t result_count, uint64_t result_stride, uint32_t cache_policy, uint64_t cache_capacity, DuallityWfst** out_wfst);',
    'duallity_phonetic_nfa_new' => 'DUALLITY_API DuallityStatus duallity_phonetic_nfa_new(const uint8_t* pattern_data, size_t pattern_len, const uint8_t* alphabet_data, size_t alphabet_len, double phonetic_weight, uint32_t cache_policy, uint64_t cache_capacity, VtResource* out_resource);',
    'duallity_phonetic_product_new_ref' => 'DUALLITY_API DuallityStatus duallity_phonetic_product_new_ref(const VtResource* dictionary, const uint8_t* pattern_data, size_t pattern_len, uint32_t maximum_distance, double phonetic_weight, double edit_weight, uint32_t cache_policy, uint64_t cache_capacity, VtResource* out_resource);',
    'duallity_phonetic_rewrite_new' => 'DUALLITY_API DuallityStatus duallity_phonetic_rewrite_new(const DuallityPhoneticRuleV1* rules, size_t rule_count, uint8_t allow_identity, uint32_t cache_policy, uint64_t cache_capacity, VtResource* out_resource);',
    'duallity_phonetic_rewrite_builtin_new' => 'DUALLITY_API DuallityStatus duallity_phonetic_rewrite_builtin_new(uint32_t locale, uint8_t allow_identity, uint32_t cache_policy, uint64_t cache_capacity, VtResource* out_resource);',
    'duallity_fzf_config_default' => 'DUALLITY_API DuallityStatus duallity_fzf_config_default(DuallityFzfConfigV1* out_config);',
    'duallity_fzf_score' => 'DUALLITY_API DuallityStatus duallity_fzf_score(const uint8_t* query_data, size_t query_len, const uint8_t* candidate_data, size_t candidate_len, const DuallityFzfConfigV1* options, DuallityFzfScoreV1* out_score);',
    'duallity_fzf_wfst_new_ref' => 'DUALLITY_API DuallityStatus duallity_fzf_wfst_new_ref(const VtResource* dictionary, const uint8_t* query_data, size_t query_len, const DuallityFzfConfigV1* options, DuallityWfst** out_wfst);',
    'duallity_fzf_wfst_config_get' => 'DUALLITY_API DuallityStatus duallity_fzf_wfst_config_get(const DuallityWfst* wfst, DuallityFzfConfigV1* out_config);',
    'duallity_fzf_rank_ref' => 'DUALLITY_API DuallityStatus duallity_fzf_rank_ref(const VtResource* dictionary, const uint8_t* query_data, size_t query_len, const DuallityFzfConfigV1* options, DuallityFzfRanking** out_ranking);',
    'duallity_fzf_ranking_len' => 'DUALLITY_API DuallityStatus duallity_fzf_ranking_len(const DuallityFzfRanking* ranking, uint64_t* out_len);',
    'duallity_fzf_ranking_get' => 'DUALLITY_API DuallityStatus duallity_fzf_ranking_get(const DuallityFzfRanking* ranking, uint64_t index, DuallityFzfHitV1* out_hit);',
    'duallity_fzf_ranking_statistics' => 'DUALLITY_API DuallityStatus duallity_fzf_ranking_statistics(const DuallityFzfRanking* ranking, DuallityFzfStatisticsV1* out_stats);',
    'duallity_fzf_ranking_free' => 'DUALLITY_API void duallity_fzf_ranking_free(DuallityFzfRanking* ranking);',
);

our constant FUNCTION-SINCE-API-REVISION is export = Map.new(
    'duallity_abi_version' => 1,
    'duallity_api_revision' => 1,
    'duallity_last_error_message' => 1,
    'duallity_wfst_new' => 1,
    'duallity_wfst_new_ref' => 2,
    'duallity_wfst_free' => 1,
    'duallity_wfst_resource' => 1,
    'duallity_resource_release' => 1,
    'duallity_wfst_options_default' => 3,
    'duallity_wfst_new_configured_ref' => 3,
    'duallity_wfst_options_get' => 3,
    'duallity_wfst_cache_statistics' => 3,
    'duallity_wfst_cache_clear' => 3,
    'duallity_wfst_cache_set_policy' => 3,
    'duallity_wallbreaker_wfst_new_results' => 5,
    'duallity_phonetic_nfa_new' => 4,
    'duallity_phonetic_product_new_ref' => 4,
    'duallity_phonetic_rewrite_new' => 4,
    'duallity_phonetic_rewrite_builtin_new' => 4,
    'duallity_fzf_config_default' => 6,
    'duallity_fzf_score' => 6,
    'duallity_fzf_wfst_new_ref' => 6,
    'duallity_fzf_wfst_config_get' => 6,
    'duallity_fzf_rank_ref' => 6,
    'duallity_fzf_ranking_len' => 6,
    'duallity_fzf_ranking_get' => 6,
    'duallity_fzf_ranking_statistics' => 6,
    'duallity_fzf_ranking_free' => 6,
);

our constant FUNCTION-OWNERSHIP is export = Map.new(
    'duallity_abi_version:return' => 'value',
    'duallity_api_revision:return' => 'value',
    'duallity_last_error_message:return' => 'borrowed-thread-local-until-next-boundary-call',
    'duallity_wfst_new:return' => 'value',
    'duallity_wfst_new:dictionary' => 'borrowed-capture-snapshot',
    'duallity_wfst_new:query_data' => 'borrowed-for-call',
    'duallity_wfst_new:query_len' => 'value',
    'duallity_wfst_new:maximum_distance' => 'value',
    'duallity_wfst_new:algorithm' => 'value',
    'duallity_wfst_new:kind' => 'value',
    'duallity_wfst_new:out_wfst' => 'owned-output-on-success',
    'duallity_wfst_new_ref:return' => 'value',
    'duallity_wfst_new_ref:dictionary' => 'borrowed-capture-snapshot',
    'duallity_wfst_new_ref:query_data' => 'borrowed-for-call',
    'duallity_wfst_new_ref:query_len' => 'value',
    'duallity_wfst_new_ref:maximum_distance' => 'value',
    'duallity_wfst_new_ref:algorithm' => 'value',
    'duallity_wfst_new_ref:kind' => 'value',
    'duallity_wfst_new_ref:out_wfst' => 'owned-output-on-success',
    'duallity_wfst_free:return' => 'none',
    'duallity_wfst_free:wfst' => 'consumed-when-non-null',
    'duallity_wfst_resource:return' => 'value',
    'duallity_wfst_resource:wfst' => 'borrowed-for-call',
    'duallity_wfst_resource:out_resource' => 'owned-retain-on-success',
    'duallity_resource_release:return' => 'none',
    'duallity_resource_release:resource' => 'consumed-retain-if-valid',
    'duallity_wfst_options_default:return' => 'value',
    'duallity_wfst_options_default:out_options' => 'caller-sized-output',
    'duallity_wfst_new_configured_ref:return' => 'value',
    'duallity_wfst_new_configured_ref:dictionary' => 'borrowed-capture-snapshot',
    'duallity_wfst_new_configured_ref:query_data' => 'borrowed-for-call',
    'duallity_wfst_new_configured_ref:query_len' => 'value',
    'duallity_wfst_new_configured_ref:options' => 'borrowed-deep-copied-for-call',
    'duallity_wfst_new_configured_ref:out_wfst' => 'owned-output-on-success',
    'duallity_wfst_options_get:return' => 'value',
    'duallity_wfst_options_get:wfst' => 'borrowed-for-call',
    'duallity_wfst_options_get:out_options' => 'caller-sized-output-with-handle-borrowed-nested-pointers',
    'duallity_wfst_cache_statistics:return' => 'value',
    'duallity_wfst_cache_statistics:wfst' => 'borrowed-for-call',
    'duallity_wfst_cache_statistics:out_statistics' => 'caller-sized-output',
    'duallity_wfst_cache_clear:return' => 'value',
    'duallity_wfst_cache_clear:wfst' => 'borrowed-for-call',
    'duallity_wfst_cache_set_policy:return' => 'value',
    'duallity_wfst_cache_set_policy:wfst' => 'borrowed-for-call',
    'duallity_wfst_cache_set_policy:policy' => 'value',
    'duallity_wfst_cache_set_policy:capacity' => 'value',
    'duallity_wallbreaker_wfst_new_results:return' => 'value',
    'duallity_wallbreaker_wfst_new_results:query_data' => 'borrowed-for-call',
    'duallity_wallbreaker_wfst_new_results:query_len' => 'value',
    'duallity_wallbreaker_wfst_new_results:algorithm_value' => 'value',
    'duallity_wallbreaker_wfst_new_results:maximum_distance' => 'value',
    'duallity_wallbreaker_wfst_new_results:results' => 'borrowed-deep-copied-for-call',
    'duallity_wallbreaker_wfst_new_results:result_count' => 'value',
    'duallity_wallbreaker_wfst_new_results:result_stride' => 'value',
    'duallity_wallbreaker_wfst_new_results:cache_policy' => 'value',
    'duallity_wallbreaker_wfst_new_results:cache_capacity' => 'value',
    'duallity_wallbreaker_wfst_new_results:out_wfst' => 'owned-output-on-success',
    'duallity_phonetic_nfa_new:return' => 'value',
    'duallity_phonetic_nfa_new:pattern_data' => 'borrowed-for-call',
    'duallity_phonetic_nfa_new:pattern_len' => 'value',
    'duallity_phonetic_nfa_new:alphabet_data' => 'borrowed-for-call',
    'duallity_phonetic_nfa_new:alphabet_len' => 'value',
    'duallity_phonetic_nfa_new:phonetic_weight' => 'value',
    'duallity_phonetic_nfa_new:cache_policy' => 'value',
    'duallity_phonetic_nfa_new:cache_capacity' => 'value',
    'duallity_phonetic_nfa_new:out_resource' => 'owned-output-on-success',
    'duallity_phonetic_product_new_ref:return' => 'value',
    'duallity_phonetic_product_new_ref:dictionary' => 'borrowed-capture-snapshot',
    'duallity_phonetic_product_new_ref:pattern_data' => 'borrowed-for-call',
    'duallity_phonetic_product_new_ref:pattern_len' => 'value',
    'duallity_phonetic_product_new_ref:maximum_distance' => 'value',
    'duallity_phonetic_product_new_ref:phonetic_weight' => 'value',
    'duallity_phonetic_product_new_ref:edit_weight' => 'value',
    'duallity_phonetic_product_new_ref:cache_policy' => 'value',
    'duallity_phonetic_product_new_ref:cache_capacity' => 'value',
    'duallity_phonetic_product_new_ref:out_resource' => 'owned-output-on-success',
    'duallity_phonetic_rewrite_new:return' => 'value',
    'duallity_phonetic_rewrite_new:rules' => 'borrowed-deep-copied-for-call',
    'duallity_phonetic_rewrite_new:rule_count' => 'value',
    'duallity_phonetic_rewrite_new:allow_identity' => 'value',
    'duallity_phonetic_rewrite_new:cache_policy' => 'value',
    'duallity_phonetic_rewrite_new:cache_capacity' => 'value',
    'duallity_phonetic_rewrite_new:out_resource' => 'owned-output-on-success',
    'duallity_phonetic_rewrite_builtin_new:return' => 'value',
    'duallity_phonetic_rewrite_builtin_new:locale' => 'value',
    'duallity_phonetic_rewrite_builtin_new:allow_identity' => 'value',
    'duallity_phonetic_rewrite_builtin_new:cache_policy' => 'value',
    'duallity_phonetic_rewrite_builtin_new:cache_capacity' => 'value',
    'duallity_phonetic_rewrite_builtin_new:out_resource' => 'owned-output-on-success',
    'duallity_fzf_config_default:return' => 'value',
    'duallity_fzf_config_default:out_config' => 'caller-sized-output',
    'duallity_fzf_score:return' => 'value',
    'duallity_fzf_score:query_data' => 'borrowed-for-call',
    'duallity_fzf_score:query_len' => 'value',
    'duallity_fzf_score:candidate_data' => 'borrowed-for-call',
    'duallity_fzf_score:candidate_len' => 'value',
    'duallity_fzf_score:options' => 'borrowed-for-call',
    'duallity_fzf_score:out_score' => 'caller-sized-output',
    'duallity_fzf_wfst_new_ref:return' => 'value',
    'duallity_fzf_wfst_new_ref:dictionary' => 'borrowed-capture-snapshot',
    'duallity_fzf_wfst_new_ref:query_data' => 'borrowed-for-call',
    'duallity_fzf_wfst_new_ref:query_len' => 'value',
    'duallity_fzf_wfst_new_ref:options' => 'borrowed-deep-copied-for-call',
    'duallity_fzf_wfst_new_ref:out_wfst' => 'owned-output-on-success',
    'duallity_fzf_wfst_config_get:return' => 'value',
    'duallity_fzf_wfst_config_get:wfst' => 'borrowed-for-call',
    'duallity_fzf_wfst_config_get:out_config' => 'caller-sized-output',
    'duallity_fzf_rank_ref:return' => 'value',
    'duallity_fzf_rank_ref:dictionary' => 'borrowed-capture-snapshot',
    'duallity_fzf_rank_ref:query_data' => 'borrowed-for-call',
    'duallity_fzf_rank_ref:query_len' => 'value',
    'duallity_fzf_rank_ref:options' => 'borrowed-for-call',
    'duallity_fzf_rank_ref:out_ranking' => 'owned-output-on-success',
    'duallity_fzf_ranking_len:return' => 'value',
    'duallity_fzf_ranking_len:ranking' => 'borrowed-for-call',
    'duallity_fzf_ranking_len:out_len' => 'caller-output',
    'duallity_fzf_ranking_get:return' => 'value',
    'duallity_fzf_ranking_get:ranking' => 'borrowed-for-call',
    'duallity_fzf_ranking_get:index' => 'value',
    'duallity_fzf_ranking_get:out_hit' => 'caller-sized-output-with-borrowed-text',
    'duallity_fzf_ranking_statistics:return' => 'value',
    'duallity_fzf_ranking_statistics:ranking' => 'borrowed-for-call',
    'duallity_fzf_ranking_statistics:out_stats' => 'caller-sized-output',
    'duallity_fzf_ranking_free:return' => 'none',
    'duallity_fzf_ranking_free:ranking' => 'consumed-when-non-null',
);

our constant FUNCTION-NULLABILITY is export = Map.new(
    'duallity_abi_version:return' => 'not-applicable',
    'duallity_api_revision:return' => 'not-applicable',
    'duallity_last_error_message:return' => 'non-null',
    'duallity_wfst_new:return' => 'not-applicable',
    'duallity_wfst_new:dictionary' => 'invalid-resource-rejected',
    'duallity_wfst_new:query_data' => 'nullable-if-query_len-is-zero',
    'duallity_wfst_new:query_len' => 'not-applicable',
    'duallity_wfst_new:maximum_distance' => 'not-applicable',
    'duallity_wfst_new:algorithm' => 'not-applicable',
    'duallity_wfst_new:kind' => 'not-applicable',
    'duallity_wfst_new:out_wfst' => 'non-null',
    'duallity_wfst_new_ref:return' => 'not-applicable',
    'duallity_wfst_new_ref:dictionary' => 'non-null',
    'duallity_wfst_new_ref:query_data' => 'nullable-if-query_len-is-zero',
    'duallity_wfst_new_ref:query_len' => 'not-applicable',
    'duallity_wfst_new_ref:maximum_distance' => 'not-applicable',
    'duallity_wfst_new_ref:algorithm' => 'not-applicable',
    'duallity_wfst_new_ref:kind' => 'not-applicable',
    'duallity_wfst_new_ref:out_wfst' => 'non-null',
    'duallity_wfst_free:return' => 'not-applicable',
    'duallity_wfst_free:wfst' => 'nullable',
    'duallity_wfst_resource:return' => 'not-applicable',
    'duallity_wfst_resource:wfst' => 'non-null',
    'duallity_wfst_resource:out_resource' => 'non-null',
    'duallity_resource_release:return' => 'not-applicable',
    'duallity_resource_release:resource' => 'invalid-resource-is-no-op',
    'duallity_wfst_options_default:return' => 'not-applicable',
    'duallity_wfst_options_default:out_options' => 'non-null',
    'duallity_wfst_new_configured_ref:return' => 'not-applicable',
    'duallity_wfst_new_configured_ref:dictionary' => 'non-null',
    'duallity_wfst_new_configured_ref:query_data' => 'nullable-if-query_len-is-zero',
    'duallity_wfst_new_configured_ref:query_len' => 'not-applicable',
    'duallity_wfst_new_configured_ref:options' => 'non-null',
    'duallity_wfst_new_configured_ref:out_wfst' => 'non-null',
    'duallity_wfst_options_get:return' => 'not-applicable',
    'duallity_wfst_options_get:wfst' => 'non-null',
    'duallity_wfst_options_get:out_options' => 'non-null',
    'duallity_wfst_cache_statistics:return' => 'not-applicable',
    'duallity_wfst_cache_statistics:wfst' => 'non-null',
    'duallity_wfst_cache_statistics:out_statistics' => 'non-null',
    'duallity_wfst_cache_clear:return' => 'not-applicable',
    'duallity_wfst_cache_clear:wfst' => 'non-null',
    'duallity_wfst_cache_set_policy:return' => 'not-applicable',
    'duallity_wfst_cache_set_policy:wfst' => 'non-null',
    'duallity_wfst_cache_set_policy:policy' => 'not-applicable',
    'duallity_wfst_cache_set_policy:capacity' => 'not-applicable',
    'duallity_wallbreaker_wfst_new_results:return' => 'not-applicable',
    'duallity_wallbreaker_wfst_new_results:query_data' => 'nullable-if-query_len-is-zero',
    'duallity_wallbreaker_wfst_new_results:query_len' => 'not-applicable',
    'duallity_wallbreaker_wfst_new_results:algorithm_value' => 'not-applicable',
    'duallity_wallbreaker_wfst_new_results:maximum_distance' => 'not-applicable',
    'duallity_wallbreaker_wfst_new_results:results' => 'nullable-if-result_count-is-zero',
    'duallity_wallbreaker_wfst_new_results:result_count' => 'not-applicable',
    'duallity_wallbreaker_wfst_new_results:result_stride' => 'not-applicable',
    'duallity_wallbreaker_wfst_new_results:cache_policy' => 'not-applicable',
    'duallity_wallbreaker_wfst_new_results:cache_capacity' => 'not-applicable',
    'duallity_wallbreaker_wfst_new_results:out_wfst' => 'non-null',
    'duallity_phonetic_nfa_new:return' => 'not-applicable',
    'duallity_phonetic_nfa_new:pattern_data' => 'nullable-if-pattern_len-is-zero',
    'duallity_phonetic_nfa_new:pattern_len' => 'not-applicable',
    'duallity_phonetic_nfa_new:alphabet_data' => 'null-selects-default-alphabet',
    'duallity_phonetic_nfa_new:alphabet_len' => 'not-applicable',
    'duallity_phonetic_nfa_new:phonetic_weight' => 'not-applicable',
    'duallity_phonetic_nfa_new:cache_policy' => 'not-applicable',
    'duallity_phonetic_nfa_new:cache_capacity' => 'not-applicable',
    'duallity_phonetic_nfa_new:out_resource' => 'non-null',
    'duallity_phonetic_product_new_ref:return' => 'not-applicable',
    'duallity_phonetic_product_new_ref:dictionary' => 'non-null',
    'duallity_phonetic_product_new_ref:pattern_data' => 'nullable-if-pattern_len-is-zero',
    'duallity_phonetic_product_new_ref:pattern_len' => 'not-applicable',
    'duallity_phonetic_product_new_ref:maximum_distance' => 'not-applicable',
    'duallity_phonetic_product_new_ref:phonetic_weight' => 'not-applicable',
    'duallity_phonetic_product_new_ref:edit_weight' => 'not-applicable',
    'duallity_phonetic_product_new_ref:cache_policy' => 'not-applicable',
    'duallity_phonetic_product_new_ref:cache_capacity' => 'not-applicable',
    'duallity_phonetic_product_new_ref:out_resource' => 'non-null',
    'duallity_phonetic_rewrite_new:return' => 'not-applicable',
    'duallity_phonetic_rewrite_new:rules' => 'nullable-if-rule_count-is-zero',
    'duallity_phonetic_rewrite_new:rule_count' => 'not-applicable',
    'duallity_phonetic_rewrite_new:allow_identity' => 'not-applicable',
    'duallity_phonetic_rewrite_new:cache_policy' => 'not-applicable',
    'duallity_phonetic_rewrite_new:cache_capacity' => 'not-applicable',
    'duallity_phonetic_rewrite_new:out_resource' => 'non-null',
    'duallity_phonetic_rewrite_builtin_new:return' => 'not-applicable',
    'duallity_phonetic_rewrite_builtin_new:locale' => 'not-applicable',
    'duallity_phonetic_rewrite_builtin_new:allow_identity' => 'not-applicable',
    'duallity_phonetic_rewrite_builtin_new:cache_policy' => 'not-applicable',
    'duallity_phonetic_rewrite_builtin_new:cache_capacity' => 'not-applicable',
    'duallity_phonetic_rewrite_builtin_new:out_resource' => 'non-null',
    'duallity_fzf_config_default:return' => 'not-applicable',
    'duallity_fzf_config_default:out_config' => 'non-null',
    'duallity_fzf_score:return' => 'not-applicable',
    'duallity_fzf_score:query_data' => 'nullable-if-query_len-is-zero',
    'duallity_fzf_score:query_len' => 'not-applicable',
    'duallity_fzf_score:candidate_data' => 'nullable-if-candidate_len-is-zero',
    'duallity_fzf_score:candidate_len' => 'not-applicable',
    'duallity_fzf_score:options' => 'non-null',
    'duallity_fzf_score:out_score' => 'non-null',
    'duallity_fzf_wfst_new_ref:return' => 'not-applicable',
    'duallity_fzf_wfst_new_ref:dictionary' => 'non-null',
    'duallity_fzf_wfst_new_ref:query_data' => 'nullable-if-query_len-is-zero',
    'duallity_fzf_wfst_new_ref:query_len' => 'not-applicable',
    'duallity_fzf_wfst_new_ref:options' => 'non-null',
    'duallity_fzf_wfst_new_ref:out_wfst' => 'non-null',
    'duallity_fzf_wfst_config_get:return' => 'not-applicable',
    'duallity_fzf_wfst_config_get:wfst' => 'non-null',
    'duallity_fzf_wfst_config_get:out_config' => 'non-null',
    'duallity_fzf_rank_ref:return' => 'not-applicable',
    'duallity_fzf_rank_ref:dictionary' => 'non-null',
    'duallity_fzf_rank_ref:query_data' => 'nullable-if-query_len-is-zero',
    'duallity_fzf_rank_ref:query_len' => 'not-applicable',
    'duallity_fzf_rank_ref:options' => 'non-null',
    'duallity_fzf_rank_ref:out_ranking' => 'non-null',
    'duallity_fzf_ranking_len:return' => 'not-applicable',
    'duallity_fzf_ranking_len:ranking' => 'non-null',
    'duallity_fzf_ranking_len:out_len' => 'non-null',
    'duallity_fzf_ranking_get:return' => 'not-applicable',
    'duallity_fzf_ranking_get:ranking' => 'non-null',
    'duallity_fzf_ranking_get:index' => 'not-applicable',
    'duallity_fzf_ranking_get:out_hit' => 'non-null',
    'duallity_fzf_ranking_statistics:return' => 'not-applicable',
    'duallity_fzf_ranking_statistics:ranking' => 'non-null',
    'duallity_fzf_ranking_statistics:out_stats' => 'non-null',
    'duallity_fzf_ranking_free:return' => 'not-applicable',
    'duallity_fzf_ranking_free:ranking' => 'nullable',
);

our constant RAKU-BINDING-EXCLUSIONS is export = Map.new(
    'duallity_wfst_new' => 'NativeCall does not portably pass the imported VtResource C aggregate by value; use duallity_wfst_new_ref',
    'duallity_resource_release' => 'Resource lifetime is owned by Vinary::Tree::Interop::Resource; NativeCall does not portably pass VtResource by value',
    'duallity_phonetic_nfa_new' => 'The phonetic Raku facade has a dedicated parity leaf and must first model Unicode buffer ownership and rule records',
    'duallity_phonetic_product_new_ref' => 'The phonetic Raku facade has a dedicated parity leaf and must first model Unicode buffer ownership and rule records',
    'duallity_phonetic_rewrite_new' => 'The phonetic Raku facade has a dedicated parity leaf and must first model Unicode buffer ownership and rule records',
    'duallity_phonetic_rewrite_builtin_new' => 'The phonetic Raku facade has a dedicated parity leaf and must first model locale selectors and resource ownership',
    'duallity_fzf_config_default' => 'Raku FZF configuration parity is tracked separately',
    'duallity_fzf_score' => 'Raku FZF scoring parity is tracked separately',
    'duallity_fzf_wfst_new_ref' => 'Raku FZF configuration parity is tracked separately',
    'duallity_fzf_wfst_config_get' => 'Raku FZF configuration parity is tracked separately',
    'duallity_fzf_rank_ref' => 'Raku FZF ranking parity is tracked separately',
    'duallity_fzf_ranking_len' => 'Raku FZF ranking parity is tracked separately',
    'duallity_fzf_ranking_get' => 'Raku FZF ranking parity is tracked separately',
    'duallity_fzf_ranking_statistics' => 'Raku FZF ranking parity is tracked separately',
    'duallity_fzf_ranking_free' => 'Raku FZF ranking parity is tracked separately',
);

sub native-library(--> Str:D) {
    return %*ENV<DUALLITY_LIBRARY> if %*ENV<DUALLITY_LIBRARY>:exists;
    $*DISTRO.is-win ?? 'duallity.dll' !!
        $*KERNEL.name eq 'darwin' ?? 'libduallity.dylib' !!
        'libduallity.so'
}

our sub duallity-abi-version(
    --> uint32
)
    is native(&native-library)
    is symbol('duallity_abi_version')
    is export(:native)
{ * }

our sub duallity-api-revision(
    --> uint32
)
    is native(&native-library)
    is symbol('duallity_api_revision')
    is export(:native)
{ * }

our sub duallity-last-error-message(
    --> Str
)
    is native(&native-library)
    is symbol('duallity_last_error_message')
    is export(:native)
{ * }

our sub duallity-wfst-new-ref(
    Vinary::Tree::Interop::RawResource,
    Pointer,
    size_t,
    size_t,
    uint32,
    uint32,
    Pointer is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('duallity_wfst_new_ref')
    is export(:native)
{ * }

our sub duallity-wfst-free(
    Pointer
)
    is native(&native-library)
    is symbol('duallity_wfst_free')
    is export(:native)
{ * }

our sub duallity-wfst-resource(
    Pointer,
    Vinary::Tree::Interop::RawResource is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('duallity_wfst_resource')
    is export(:native)
{ * }

our sub duallity-wfst-options-default(
    Pointer,
    --> uint32
)
    is native(&native-library)
    is symbol('duallity_wfst_options_default')
    is export(:native)
{ * }

our sub duallity-wfst-new-configured-ref(
    Vinary::Tree::Interop::RawResource,
    Pointer,
    size_t,
    Pointer,
    Pointer is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('duallity_wfst_new_configured_ref')
    is export(:native)
{ * }

our sub duallity-wfst-options-get(
    Pointer,
    Pointer,
    --> uint32
)
    is native(&native-library)
    is symbol('duallity_wfst_options_get')
    is export(:native)
{ * }

our sub duallity-wfst-cache-statistics(
    Pointer,
    Pointer,
    --> uint32
)
    is native(&native-library)
    is symbol('duallity_wfst_cache_statistics')
    is export(:native)
{ * }

our sub duallity-wfst-cache-clear(
    Pointer,
    --> uint32
)
    is native(&native-library)
    is symbol('duallity_wfst_cache_clear')
    is export(:native)
{ * }

our sub duallity-wfst-cache-set-policy(
    Pointer,
    uint32,
    uint64,
    --> uint32
)
    is native(&native-library)
    is symbol('duallity_wfst_cache_set_policy')
    is export(:native)
{ * }

our sub duallity-wallbreaker-wfst-new-results(
    Pointer,
    size_t,
    uint32,
    uint64,
    Pointer,
    uint64,
    uint64,
    uint32,
    uint64,
    Pointer is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('duallity_wallbreaker_wfst_new_results')
    is export(:native)
{ * }
