unit module Duallity::GeneratedAbi;

use NativeCall;
need Vinary::Tree::Interop;

# Code generated by scripts/generate-raku-abi.py from bindings/api.json
# after validating include/duallity.h; DO NOT EDIT.
our constant ABI-VERSION is export = 1;
our constant API-REVISION is export = 2;

our enum Status is export (
    OK => 0,
    INVALID-ARGUMENT => 1,
    INVALID-UTF8 => 2,
    NULL-POINTER => 3,
    PANIC => 4,
    INCOMPATIBLE-RESOURCE => 5,
    PROVIDER-ERROR => 6,
    LIMIT-EXCEEDED => 7,
);

our enum Algorithm is export (
    STANDARD => 0,
    TRANSPOSITION => 1,
    MERGE-AND-SPLIT => 2,
    DAMERAU-LEVENSHTEIN => 3,
);

our enum WfstKind is export (
    LEVENSHTEIN => 0,
    UNIVERSAL-STANDARD => 1,
    UNIVERSAL-TRANSPOSITION => 2,
    UNIVERSAL-MERGE-AND-SPLIT => 3,
    GENERALIZED-STANDARD => 4,
    GENERALIZED-TRANSPOSITION => 5,
    GENERALIZED-MERGE-AND-SPLIT => 6,
    GENERALIZED-PHONETIC => 7,
    FZF => 8,
);

our constant TYPE-KINDS is export = Map.new(
    'DuallityWfst' => 'opaque',
    'VtResource' => 'imported-struct',
);

our constant TYPE-RAKU-REPRESENTATIONS is export = Map.new(
    'DuallityWfst' => 'Pointer',
    'VtResource' => 'Vinary::Tree::Interop::RawResource',
);

our constant TYPE-OWNERSHIP is export = Map.new(
    'DuallityWfst' => 'unique-handle',
    'VtResource' => 'reference-counted-retain',
);

our constant C-SIGNATURES is export = Map.new(
    'duallity_abi_version' => 'DUALLITY_API uint32_t duallity_abi_version(void);',
    'duallity_api_revision' => 'DUALLITY_API uint32_t duallity_api_revision(void);',
    'duallity_last_error_message' => 'DUALLITY_API const char* duallity_last_error_message(void);',
    'duallity_wfst_new' => 'DUALLITY_API DuallityStatus duallity_wfst_new(VtResource dictionary, const uint8_t* query_data, size_t query_len, size_t maximum_distance, uint32_t algorithm, uint32_t kind, DuallityWfst** out_wfst);',
    'duallity_wfst_new_ref' => 'DUALLITY_API DuallityStatus duallity_wfst_new_ref(const VtResource* dictionary, const uint8_t* query_data, size_t query_len, size_t maximum_distance, uint32_t algorithm, uint32_t kind, DuallityWfst** out_wfst);',
    'duallity_wfst_free' => 'DUALLITY_API void duallity_wfst_free(DuallityWfst* wfst);',
    'duallity_wfst_resource' => 'DUALLITY_API DuallityStatus duallity_wfst_resource(const DuallityWfst* wfst, VtResource* out_resource);',
    'duallity_resource_release' => 'DUALLITY_API void duallity_resource_release(VtResource resource);',
);

our constant FUNCTION-SINCE-API-REVISION is export = Map.new(
    'duallity_abi_version' => 1,
    'duallity_api_revision' => 1,
    'duallity_last_error_message' => 1,
    'duallity_wfst_new' => 1,
    'duallity_wfst_new_ref' => 2,
    'duallity_wfst_free' => 1,
    'duallity_wfst_resource' => 1,
    'duallity_resource_release' => 1,
);

our constant FUNCTION-OWNERSHIP is export = Map.new(
    'duallity_abi_version:return' => 'value',
    'duallity_api_revision:return' => 'value',
    'duallity_last_error_message:return' => 'borrowed-thread-local-until-next-boundary-call',
    'duallity_wfst_new:return' => 'value',
    'duallity_wfst_new:dictionary' => 'borrowed-capture-snapshot',
    'duallity_wfst_new:query_data' => 'borrowed-for-call',
    'duallity_wfst_new:query_len' => 'value',
    'duallity_wfst_new:maximum_distance' => 'value',
    'duallity_wfst_new:algorithm' => 'value',
    'duallity_wfst_new:kind' => 'value',
    'duallity_wfst_new:out_wfst' => 'owned-output-on-success',
    'duallity_wfst_new_ref:return' => 'value',
    'duallity_wfst_new_ref:dictionary' => 'borrowed-capture-snapshot',
    'duallity_wfst_new_ref:query_data' => 'borrowed-for-call',
    'duallity_wfst_new_ref:query_len' => 'value',
    'duallity_wfst_new_ref:maximum_distance' => 'value',
    'duallity_wfst_new_ref:algorithm' => 'value',
    'duallity_wfst_new_ref:kind' => 'value',
    'duallity_wfst_new_ref:out_wfst' => 'owned-output-on-success',
    'duallity_wfst_free:return' => 'none',
    'duallity_wfst_free:wfst' => 'consumed-when-non-null',
    'duallity_wfst_resource:return' => 'value',
    'duallity_wfst_resource:wfst' => 'borrowed-for-call',
    'duallity_wfst_resource:out_resource' => 'owned-retain-on-success',
    'duallity_resource_release:return' => 'none',
    'duallity_resource_release:resource' => 'consumed-retain-if-valid',
);

our constant FUNCTION-NULLABILITY is export = Map.new(
    'duallity_abi_version:return' => 'not-applicable',
    'duallity_api_revision:return' => 'not-applicable',
    'duallity_last_error_message:return' => 'non-null',
    'duallity_wfst_new:return' => 'not-applicable',
    'duallity_wfst_new:dictionary' => 'invalid-resource-rejected',
    'duallity_wfst_new:query_data' => 'nullable-if-query_len-is-zero',
    'duallity_wfst_new:query_len' => 'not-applicable',
    'duallity_wfst_new:maximum_distance' => 'not-applicable',
    'duallity_wfst_new:algorithm' => 'not-applicable',
    'duallity_wfst_new:kind' => 'not-applicable',
    'duallity_wfst_new:out_wfst' => 'non-null',
    'duallity_wfst_new_ref:return' => 'not-applicable',
    'duallity_wfst_new_ref:dictionary' => 'non-null',
    'duallity_wfst_new_ref:query_data' => 'nullable-if-query_len-is-zero',
    'duallity_wfst_new_ref:query_len' => 'not-applicable',
    'duallity_wfst_new_ref:maximum_distance' => 'not-applicable',
    'duallity_wfst_new_ref:algorithm' => 'not-applicable',
    'duallity_wfst_new_ref:kind' => 'not-applicable',
    'duallity_wfst_new_ref:out_wfst' => 'non-null',
    'duallity_wfst_free:return' => 'not-applicable',
    'duallity_wfst_free:wfst' => 'nullable',
    'duallity_wfst_resource:return' => 'not-applicable',
    'duallity_wfst_resource:wfst' => 'non-null',
    'duallity_wfst_resource:out_resource' => 'non-null',
    'duallity_resource_release:return' => 'not-applicable',
    'duallity_resource_release:resource' => 'invalid-resource-is-no-op',
);

our constant RAKU-BINDING-EXCLUSIONS is export = Map.new(
    'duallity_wfst_new' => 'NativeCall does not portably pass the imported VtResource C aggregate by value; use duallity_wfst_new_ref',
    'duallity_resource_release' => 'Resource lifetime is owned by Vinary::Tree::Interop::Resource; NativeCall does not portably pass VtResource by value',
);

sub native-library(--> Str:D) {
    return %*ENV<DUALLITY_LIBRARY> if %*ENV<DUALLITY_LIBRARY>:exists;
    $*DISTRO.is-win ?? 'duallity.dll' !!
        $*KERNEL.name eq 'darwin' ?? 'libduallity.dylib' !!
        'libduallity.so'
}

our sub duallity-abi-version(
    --> uint32
)
    is native(&native-library)
    is symbol('duallity_abi_version')
    is export(:native)
{ * }

our sub duallity-api-revision(
    --> uint32
)
    is native(&native-library)
    is symbol('duallity_api_revision')
    is export(:native)
{ * }

our sub duallity-last-error-message(
    --> Str
)
    is native(&native-library)
    is symbol('duallity_last_error_message')
    is export(:native)
{ * }

our sub duallity-wfst-new-ref(
    Vinary::Tree::Interop::RawResource,
    Pointer,
    size_t,
    size_t,
    uint32,
    uint32,
    Pointer is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('duallity_wfst_new_ref')
    is export(:native)
{ * }

our sub duallity-wfst-free(
    Pointer
)
    is native(&native-library)
    is symbol('duallity_wfst_free')
    is export(:native)
{ * }

our sub duallity-wfst-resource(
    Pointer,
    Vinary::Tree::Interop::RawResource is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('duallity_wfst_resource')
    is export(:native)
{ * }
